version: '3'
networks:
  dreamerly_network:
    driver: bridge
services:
  nginx:
    container_name: nginx_my_dreamerly    
    restart: always
    build:       
      context: ./stack-fe      
    ports:
      - 3000:80
    networks:
      - dreamerly_network
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf       
  mysqldb:    
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysqldb_my_dreamerly          
    volumes:
        - my-datavolume:/var/lib/mysql        
    environment:
        - MYSQL_ROOT_USER:root
        - MYSQL_ROOT_PASSWORD:dreamerly@246
        - MYSQL_DATABASE:my_dreamerly
        - MYSQL_ROOT_HOST:'%'  
    ports:
      - 3307:3306  
    networks:
      - dreamerly_network
  backend:
    depends_on:
      - mysqldb
    container_name: backend_my_dreamerly  
    build: 
      context: ./stack-be
    environment:        
      - DATABASE_PORT:3307   
      - HOST:host.docker.internal
    ports:
      - 8000:8000
    networks:
      - dreamerly_network
volumes:
  my-datavolume:
# docker compose -p my-dreamerly up -d