version: '3'
networks:
  bridge:
    driver: bridge
services:
  nginx:
    container_name: nginx_my_dreamerly    
    restart: always
    build:       
      context: ./stack-fe 
    ports:
      - 3000:80 
    networks:
      - bridge   
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf       
  mysqldb:    
    image: mysql:5.7       
    container_name: mysqldb_my_dreamerly   
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: dreamerly246
      MYSQL_DATABASE: my_dreamerly         
    volumes:
        - my-datavolume:/var/lib/mysql        
    networks:
      - bridge   
    ports:
      - 3307:3306        
  backend:
    depends_on:
      - mysqldb
    container_name: backend_my_dreamerly  
    build: 
      context: ./stack-be
    ports:
      - 7000:8000    
    networks:
      - bridge   
    environment:        
      - DATABASE_PORT:3307   
      - HOST:host.docker.internal    
volumes:
  my-datavolume:
# docker compose -p my-dreamerly up -d