version: '3'
networks:
  bridge:
    driver: bridge
services:
  nginx:
    container_name: nginx_my_dreamerly    
    restart: always
    build:       
      context: ./stack-fe 
    ports:
      - 3000:80 
    networks:
      - bridge       
volumes:
  my-datavolume:
# docker compose -p my-dreamerly up -d