version: '3'
networks:
  bridge:
    driver: bridge
services:
  nginx:
    container_name: nginx_my_dreamerly    
    restart: always
    build:       
      context: ./stack-fe 
    ports:
      - 9821:80 
    networks:
      - bridge   
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf       
  mysqldb:    
    image: mysql:5.7       
    container_name: mysqldb_my_dreamerly   
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: dreamerly246
      MYSQL_DATABASE: my_dreamerly         
    volumes:
        - my_data:/var/lib/mysql        
    networks:
      - bridge   
    ports:
      - 4561:3306        
  backend:
    depends_on:
      - mysqldb
    container_name: backend_my_dreamerly  
    build: 
      context: ./stack-be
    ports:
      - 7201:8000    
    networks:
      - bridge       
volumes:
  my_data:
# docker compose -p my-dreamerly up -d